apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp-container
    image: pratiak/final_jar:1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name:  node-service
spec:
  selector:
    app:  myapp
  type:  NodePort
  ports:
  - targetPort:  8080
    port:  8080
    nodePort: 31000
